apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: curlftpfs
  name: curlftpfs
spec:
  replicas: 1
  selector:
    app: curlftpfs
    deploymentconfig: curlftpfs
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curlftpfs
        deploymentconfig: curlftpfs
    spec:
      containers:
      - image: docker-registry.default.svc.cluster.local:5000/fuse-mount/curlftpfs@latest
        imagePullPolicy: Always
        name: curlftpfs
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fuse-mount
      serviceAccountName: fuse-mount
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - curlftpfs
      from:
        kind: ImageStreamTag
        name: curlftpfs:latest
        namespace: fuse-mount
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
