apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: s3fusefs
  name: s3fusefs
spec:
  replicas: 1
  selector:
    app: s3fusefs
    deploymentconfig: s3fusefs
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: s3fusefs
        deploymentconfig: s3fusefs
    spec:
      containers:
      - image: 172.30.151.247:5000/fuse-test/s3fusefs@sha256:f2cc5d0fa07dec45f319f3e90cd89258c37774cb2dde44fea5c474ad8d2e20e1
        imagePullPolicy: Always
        name: s3fusefs
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fuse-mount
      serviceAccountName: fuse-mount
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - s3fusefs
      from:
        kind: ImageStreamTag
        name: s3fusefs:latest
        namespace: fuse-test
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
