apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: s3fusefs
  name: s3fusefs
spec:
  replicas: 1
  selector:
    app: s3fusefs
    deploymentconfig: s3fusefs
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: s3fusefs
        deploymentconfig: s3fusefs
    spec:
      containers:
      - image: docker-registry.default.svc.cluster.local:5000/fuse-mount/s3fusefs@latest
        imagePullPolicy: Always
        name: s3fusefs
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: S3_USER
          valueFrom:
            secretKeyRef:
              name: s3-bucket
              key: S3_USER
        - name: S3_PASSWORD
          valueFrom:
            secretKeyRef:
              name: s3-bucket
              key: S3_PASSWORD
        - name: S3_BUCKET
          required: yes
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fuse-mount
      serviceAccountName: fuse-mount
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - s3fusefs
      from:
        kind: ImageStreamTag
        name: s3fusefs:latest
        namespace: fuse-mount
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
