apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: s3fusefs
  name: s3fusefs
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker-registry.default.svc.cluster.local:5000/fuse-test/s3fusefs:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
